language: objective-c
before_install:
  - export LANG=en_US.UTF-8
  - gem install cocoapods --no-ri --no-rdoc
  - gem install xcpretty --no-ri --no-rdoc
  - cd Tests
  - pod install
  - cd ..
script: rake test

